// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_2mNBR5Q1SbMPAsYIhoUg-aUEAPE29es',
    appId: '1:637572033364:web:958950aef928080bf6b6c1',
    messagingSenderId: '637572033364',
    projectId: 'spotify-b9840',
    authDomain: 'spotify-b9840.firebaseapp.com',
    storageBucket: 'spotify-b9840.firebasestorage.app',
    measurementId: 'G-KMPHXLEXL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgNA-8DmO0NSnSpruH7twP_2jAyXzhmx0',
    appId: '1:637572033364:android:b64752445e8f64f6f6b6c1',
    messagingSenderId: '637572033364',
    projectId: 'spotify-b9840',
    storageBucket: 'spotify-b9840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYwrxjDpOpJ9-8JEUFOyJ0IGvYiaBM5o8',
    appId: '1:637572033364:ios:17438329851162b8f6b6c1',
    messagingSenderId: '637572033364',
    projectId: 'spotify-b9840',
    storageBucket: 'spotify-b9840.firebasestorage.app',
    androidClientId: '637572033364-9fhtsq0geh1dvtnlkeg5u1q27jgcljs8.apps.googleusercontent.com',
    iosClientId: '637572033364-1suih5g3gbt2udn71hk3v7oi79c24hj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYwrxjDpOpJ9-8JEUFOyJ0IGvYiaBM5o8',
    appId: '1:637572033364:ios:17438329851162b8f6b6c1',
    messagingSenderId: '637572033364',
    projectId: 'spotify-b9840',
    storageBucket: 'spotify-b9840.firebasestorage.app',
    androidClientId: '637572033364-9fhtsq0geh1dvtnlkeg5u1q27jgcljs8.apps.googleusercontent.com',
    iosClientId: '637572033364-1suih5g3gbt2udn71hk3v7oi79c24hj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_2mNBR5Q1SbMPAsYIhoUg-aUEAPE29es',
    appId: '1:637572033364:web:3441ca129f1a4309f6b6c1',
    messagingSenderId: '637572033364',
    projectId: 'spotify-b9840',
    authDomain: 'spotify-b9840.firebaseapp.com',
    storageBucket: 'spotify-b9840.firebasestorage.app',
    measurementId: 'G-F806402XMD',
  );
}
